/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.analysis;

import eu.serscis.sam.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseABehaviour(ABehaviour node);
    void caseAExtends(AExtends node);
    void caseAClassBody(AClassBody node);
    void caseAField(AField node);
    void caseAType(AType node);
    void caseAMethod(AMethod node);
    void caseACode(ACode node);
    void caseAAssign(AAssign node);
    void caseANewStatement(ANewStatement node);
    void caseACallStatement(ACallStatement node);
    void caseAReturnStatement(AReturnStatement node);
    void caseANewExpr(ANewExpr node);
    void caseACallExpr(ACallExpr node);
    void caseAArgs(AArgs node);

    void caseTNumber(TNumber node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTPublicTok(TPublicTok node);
    void caseTPrivateTok(TPrivateTok node);
    void caseTExtendsTok(TExtendsTok node);
    void caseTNew(TNew node);
    void caseTReturn(TReturn node);
    void caseTClassTok(TClassTok node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTEq(TEq node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseTComma(TComma node);
    void caseTGoal(TGoal node);
    void caseTSemi(TSemi node);
    void caseTName(TName node);
    void caseEOF(EOF node);
}
