/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.parser;

import eu.serscis.sam.lexer.*;
import eu.serscis.sam.node.*;
import eu.serscis.sam.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AProgram */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce ABehaviourToplevel */
		    {
			ArrayList list = new1();
			push(goTo(1), list, false);
		    }
		    break;
                    case 2: /* reduce AImportToplevel */
		    {
			ArrayList list = new2();
			push(goTo(1), list, false);
		    }
		    break;
                    case 3: /* reduce AFactToplevel */
		    {
			ArrayList list = new3();
			push(goTo(1), list, false);
		    }
		    break;
                    case 4: /* reduce ARuleToplevel */
		    {
			ArrayList list = new4();
			push(goTo(1), list, false);
		    }
		    break;
                    case 5: /* reduce AQueryToplevel */
		    {
			ArrayList list = new5();
			push(goTo(1), list, false);
		    }
		    break;
                    case 6: /* reduce AImport */
		    {
			ArrayList list = new6();
			push(goTo(2), list, false);
		    }
		    break;
                    case 7: /* reduce AFact */
		    {
			ArrayList list = new7();
			push(goTo(3), list, false);
		    }
		    break;
                    case 8: /* reduce ARule */
		    {
			ArrayList list = new8();
			push(goTo(4), list, false);
		    }
		    break;
                    case 9: /* reduce AAliterals1Literals */
		    {
			ArrayList list = new9();
			push(goTo(5), list, false);
		    }
		    break;
                    case 10: /* reduce AAliterals2Literals */
		    {
			ArrayList list = new10();
			push(goTo(5), list, false);
		    }
		    break;
                    case 11: /* reduce ALiteralTail */
		    {
			ArrayList list = new11();
			push(goTo(6), list, false);
		    }
		    break;
                    case 12: /* reduce APositiveLiteral */
		    {
			ArrayList list = new12();
			push(goTo(7), list, false);
		    }
		    break;
                    case 13: /* reduce ANegativeLiteral */
		    {
			ArrayList list = new13();
			push(goTo(7), list, false);
		    }
		    break;
                    case 14: /* reduce ANullaryAtom */
		    {
			ArrayList list = new14();
			push(goTo(8), list, false);
		    }
		    break;
                    case 15: /* reduce ANormalAtom */
		    {
			ArrayList list = new15();
			push(goTo(8), list, false);
		    }
		    break;
                    case 16: /* reduce ABuiltinAtom */
		    {
			ArrayList list = new16();
			push(goTo(8), list, false);
		    }
		    break;
                    case 17: /* reduce AAterms1Terms */
		    {
			ArrayList list = new17();
			push(goTo(9), list, false);
		    }
		    break;
                    case 18: /* reduce AAterms2Terms */
		    {
			ArrayList list = new18();
			push(goTo(9), list, false);
		    }
		    break;
                    case 19: /* reduce ATermTail */
		    {
			ArrayList list = new19();
			push(goTo(10), list, false);
		    }
		    break;
                    case 20: /* reduce AVarTerm */
		    {
			ArrayList list = new20();
			push(goTo(11), list, false);
		    }
		    break;
                    case 21: /* reduce AStringTerm */
		    {
			ArrayList list = new21();
			push(goTo(11), list, false);
		    }
		    break;
                    case 22: /* reduce ACompositeTerm */
		    {
			ArrayList list = new22();
			push(goTo(11), list, false);
		    }
		    break;
                    case 23: /* reduce AQuery */
		    {
			ArrayList list = new23();
			push(goTo(12), list, false);
		    }
		    break;
                    case 24: /* reduce ANamedPattern */
		    {
			ArrayList list = new24();
			push(goTo(13), list, false);
		    }
		    break;
                    case 25: /* reduce AAnyPattern */
		    {
			ArrayList list = new25();
			push(goTo(13), list, false);
		    }
		    break;
                    case 26: /* reduce AAbehaviour1Behaviour */
		    {
			ArrayList list = new26();
			push(goTo(14), list, false);
		    }
		    break;
                    case 27: /* reduce AAbehaviour2Behaviour */
		    {
			ArrayList list = new27();
			push(goTo(14), list, false);
		    }
		    break;
                    case 28: /* reduce AExtends */
		    {
			ArrayList list = new28();
			push(goTo(15), list, false);
		    }
		    break;
                    case 29: /* reduce AAclassbody1ClassBody */
		    {
			ArrayList list = new29();
			push(goTo(16), list, false);
		    }
		    break;
                    case 30: /* reduce AAclassbody2ClassBody */
		    {
			ArrayList list = new30();
			push(goTo(16), list, false);
		    }
		    break;
                    case 31: /* reduce AAclassbody3ClassBody */
		    {
			ArrayList list = new31();
			push(goTo(16), list, false);
		    }
		    break;
                    case 32: /* reduce AAclassbody4ClassBody */
		    {
			ArrayList list = new32();
			push(goTo(16), list, false);
		    }
		    break;
                    case 33: /* reduce AField */
		    {
			ArrayList list = new33();
			push(goTo(17), list, false);
		    }
		    break;
                    case 34: /* reduce AType */
		    {
			ArrayList list = new34();
			push(goTo(18), list, false);
		    }
		    break;
                    case 35: /* reduce AAmethod1Method */
		    {
			ArrayList list = new35();
			push(goTo(19), list, false);
		    }
		    break;
                    case 36: /* reduce AAmethod2Method */
		    {
			ArrayList list = new36();
			push(goTo(19), list, false);
		    }
		    break;
                    case 37: /* reduce AAmethod3Method */
		    {
			ArrayList list = new37();
			push(goTo(19), list, false);
		    }
		    break;
                    case 38: /* reduce AAmethod4Method */
		    {
			ArrayList list = new38();
			push(goTo(19), list, false);
		    }
		    break;
                    case 39: /* reduce AAmethod5Method */
		    {
			ArrayList list = new39();
			push(goTo(19), list, false);
		    }
		    break;
                    case 40: /* reduce AAmethod6Method */
		    {
			ArrayList list = new40();
			push(goTo(19), list, false);
		    }
		    break;
                    case 41: /* reduce AAmethod7Method */
		    {
			ArrayList list = new41();
			push(goTo(19), list, false);
		    }
		    break;
                    case 42: /* reduce AAmethod8Method */
		    {
			ArrayList list = new42();
			push(goTo(19), list, false);
		    }
		    break;
                    case 43: /* reduce AAcode1Code */
		    {
			ArrayList list = new43();
			push(goTo(20), list, false);
		    }
		    break;
                    case 44: /* reduce AAcode2Code */
		    {
			ArrayList list = new44();
			push(goTo(20), list, false);
		    }
		    break;
                    case 45: /* reduce AAassign1Assign */
		    {
			ArrayList list = new45();
			push(goTo(21), list, false);
		    }
		    break;
                    case 46: /* reduce AAassign2Assign */
		    {
			ArrayList list = new46();
			push(goTo(21), list, false);
		    }
		    break;
                    case 47: /* reduce AAassignstatement1Statement */
		    {
			ArrayList list = new47();
			push(goTo(22), list, false);
		    }
		    break;
                    case 48: /* reduce AAassignstatement2Statement */
		    {
			ArrayList list = new48();
			push(goTo(22), list, false);
		    }
		    break;
                    case 49: /* reduce ADeclStatement */
		    {
			ArrayList list = new49();
			push(goTo(22), list, false);
		    }
		    break;
                    case 50: /* reduce AReturnStatement */
		    {
			ArrayList list = new50();
			push(goTo(22), list, false);
		    }
		    break;
                    case 51: /* reduce AAnewexpr1Expr */
		    {
			ArrayList list = new51();
			push(goTo(23), list, false);
		    }
		    break;
                    case 52: /* reduce AAnewexpr2Expr */
		    {
			ArrayList list = new52();
			push(goTo(23), list, false);
		    }
		    break;
                    case 53: /* reduce AAcallexpr1Expr */
		    {
			ArrayList list = new53();
			push(goTo(23), list, false);
		    }
		    break;
                    case 54: /* reduce AAcallexpr2Expr */
		    {
			ArrayList list = new54();
			push(goTo(23), list, false);
		    }
		    break;
                    case 55: /* reduce ACopyExpr */
		    {
			ArrayList list = new55();
			push(goTo(23), list, false);
		    }
		    break;
                    case 56: /* reduce AAargs1Args */
		    {
			ArrayList list = new56();
			push(goTo(24), list, false);
		    }
		    break;
                    case 57: /* reduce AAargs2Args */
		    {
			ArrayList list = new57();
			push(goTo(24), list, false);
		    }
		    break;
                    case 58: /* reduce AArgsTail */
		    {
			ArrayList list = new58();
			push(goTo(25), list, false);
		    }
		    break;
                    case 59: /* reduce AParam */
		    {
			ArrayList list = new59();
			push(goTo(26), list, false);
		    }
		    break;
                    case 60: /* reduce AAparams1Params */
		    {
			ArrayList list = new60();
			push(goTo(27), list, false);
		    }
		    break;
                    case 61: /* reduce AAparams2Params */
		    {
			ArrayList list = new61();
			push(goTo(27), list, false);
		    }
		    break;
                    case 62: /* reduce AParamsTail */
		    {
			ArrayList list = new62();
			push(goTo(28), list, false);
		    }
		    break;
                    case 63: /* reduce ATerminal$Toplevel */
		    {
			ArrayList list = new63();
			push(goTo(29), list, true);
		    }
		    break;
                    case 64: /* reduce ANonTerminal$Toplevel */
		    {
			ArrayList list = new64();
			push(goTo(29), list, true);
		    }
		    break;
                    case 65: /* reduce ATerminal$LiteralTail */
		    {
			ArrayList list = new65();
			push(goTo(30), list, true);
		    }
		    break;
                    case 66: /* reduce ANonTerminal$LiteralTail */
		    {
			ArrayList list = new66();
			push(goTo(30), list, true);
		    }
		    break;
                    case 67: /* reduce ATerminal$TermTail */
		    {
			ArrayList list = new67();
			push(goTo(31), list, true);
		    }
		    break;
                    case 68: /* reduce ANonTerminal$TermTail */
		    {
			ArrayList list = new68();
			push(goTo(31), list, true);
		    }
		    break;
                    case 69: /* reduce ATerminal$Field */
		    {
			ArrayList list = new69();
			push(goTo(32), list, true);
		    }
		    break;
                    case 70: /* reduce ANonTerminal$Field */
		    {
			ArrayList list = new70();
			push(goTo(32), list, true);
		    }
		    break;
                    case 71: /* reduce ATerminal$Method */
		    {
			ArrayList list = new71();
			push(goTo(33), list, true);
		    }
		    break;
                    case 72: /* reduce ANonTerminal$Method */
		    {
			ArrayList list = new72();
			push(goTo(33), list, true);
		    }
		    break;
                    case 73: /* reduce ATerminal$Statement */
		    {
			ArrayList list = new73();
			push(goTo(34), list, true);
		    }
		    break;
                    case 74: /* reduce ANonTerminal$Statement */
		    {
			ArrayList list = new74();
			push(goTo(34), list, true);
		    }
		    break;
                    case 75: /* reduce ATerminal$ArgsTail */
		    {
			ArrayList list = new75();
			push(goTo(35), list, true);
		    }
		    break;
                    case 76: /* reduce ANonTerminal$ArgsTail */
		    {
			ArrayList list = new76();
			push(goTo(35), list, true);
		    }
		    break;
                    case 77: /* reduce ATerminal$ParamsTail */
		    {
			ArrayList list = new77();
			push(goTo(36), list, true);
		    }
		    break;
                    case 78: /* reduce ANonTerminal$ParamsTail */
		    {
			ArrayList list = new78();
			push(goTo(36), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogramNode1 = new AProgram(listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce ABehaviourToplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PToplevel ptoplevelNode1;
        {
            // Block
        PBehaviour pbehaviourNode2;
        pbehaviourNode2 = (PBehaviour)nodeArrayList1.get(0);

        ptoplevelNode1 = new ABehaviourToplevel(pbehaviourNode2);
        }
	nodeList.add(ptoplevelNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AImportToplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PToplevel ptoplevelNode1;
        {
            // Block
        PImport pimportNode2;
        pimportNode2 = (PImport)nodeArrayList1.get(0);

        ptoplevelNode1 = new AImportToplevel(pimportNode2);
        }
	nodeList.add(ptoplevelNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AFactToplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PToplevel ptoplevelNode1;
        {
            // Block
        PFact pfactNode2;
        pfactNode2 = (PFact)nodeArrayList1.get(0);

        ptoplevelNode1 = new AFactToplevel(pfactNode2);
        }
	nodeList.add(ptoplevelNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce ARuleToplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PToplevel ptoplevelNode1;
        {
            // Block
        PRule pruleNode2;
        pruleNode2 = (PRule)nodeArrayList1.get(0);

        ptoplevelNode1 = new ARuleToplevel(pruleNode2);
        }
	nodeList.add(ptoplevelNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AQueryToplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PToplevel ptoplevelNode1;
        {
            // Block
        PQuery pqueryNode2;
        pqueryNode2 = (PQuery)nodeArrayList1.get(0);

        ptoplevelNode1 = new AQueryToplevel(pqueryNode2);
        }
	nodeList.add(ptoplevelNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AImport */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PImport pimportNode1;
        {
            // Block
        TImportTok timporttokNode2;
        TStringLiteral tstringliteralNode3;
        TDot tdotNode4;
        timporttokNode2 = (TImportTok)nodeArrayList1.get(0);
        tstringliteralNode3 = (TStringLiteral)nodeArrayList2.get(0);
        tdotNode4 = (TDot)nodeArrayList3.get(0);

        pimportNode1 = new AImport(timporttokNode2, tstringliteralNode3, tdotNode4);
        }
	nodeList.add(pimportNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AFact */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFact pfactNode1;
        {
            // Block
        PAtom patomNode2;
        TDot tdotNode3;
        patomNode2 = (PAtom)nodeArrayList1.get(0);
        tdotNode3 = (TDot)nodeArrayList2.get(0);

        pfactNode1 = new AFact(patomNode2, tdotNode3);
        }
	nodeList.add(pfactNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce ARule */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PRule pruleNode1;
        {
            // Block
        PAtom patomNode2;
        TIfDl tifdlNode3;
        PLiterals pliteralsNode4;
        TDot tdotNode5;
        patomNode2 = (PAtom)nodeArrayList1.get(0);
        tifdlNode3 = (TIfDl)nodeArrayList2.get(0);
        pliteralsNode4 = (PLiterals)nodeArrayList3.get(0);
        tdotNode5 = (TDot)nodeArrayList4.get(0);

        pruleNode1 = new ARule(patomNode2, tifdlNode3, pliteralsNode4, tdotNode5);
        }
	nodeList.add(pruleNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AAliterals1Literals */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiterals pliteralsNode1;
        {
            // Block
        PLiteral pliteralNode2;
        LinkedList listNode3 = new LinkedList();
        pliteralNode2 = (PLiteral)nodeArrayList1.get(0);
        {
            // Block
        }

        pliteralsNode1 = new ALiterals(pliteralNode2, listNode3);
        }
	nodeList.add(pliteralsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AAliterals2Literals */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiterals pliteralsNode1;
        {
            // Block
        PLiteral pliteralNode2;
        LinkedList listNode4 = new LinkedList();
        pliteralNode2 = (PLiteral)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pliteralsNode1 = new ALiterals(pliteralNode2, listNode4);
        }
	nodeList.add(pliteralsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce ALiteralTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteralTail pliteraltailNode1;
        {
            // Block
        TComma tcommaNode2;
        PLiteral pliteralNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pliteralNode3 = (PLiteral)nodeArrayList2.get(0);

        pliteraltailNode1 = new ALiteralTail(tcommaNode2, pliteralNode3);
        }
	nodeList.add(pliteraltailNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce APositiveLiteral */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteral pliteralNode1;
        {
            // Block
        PAtom patomNode2;
        patomNode2 = (PAtom)nodeArrayList1.get(0);

        pliteralNode1 = new APositiveLiteral(patomNode2);
        }
	nodeList.add(pliteralNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce ANegativeLiteral */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteral pliteralNode1;
        {
            // Block
        TBang tbangNode2;
        PAtom patomNode3;
        tbangNode2 = (TBang)nodeArrayList1.get(0);
        patomNode3 = (PAtom)nodeArrayList2.get(0);

        pliteralNode1 = new ANegativeLiteral(tbangNode2, patomNode3);
        }
	nodeList.add(pliteralNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce ANullaryAtom */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAtom patomNode1;
        {
            // Block
        TName tnameNode2;
        tnameNode2 = (TName)nodeArrayList1.get(0);

        patomNode1 = new ANullaryAtom(tnameNode2);
        }
	nodeList.add(patomNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce ANormalAtom */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAtom patomNode1;
        {
            // Block
        TName tnameNode2;
        TLPar tlparNode3;
        PTerms ptermsNode4;
        TRPar trparNode5;
        tnameNode2 = (TName)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        ptermsNode4 = (PTerms)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);

        patomNode1 = new ANormalAtom(tnameNode2, tlparNode3, ptermsNode4, trparNode5);
        }
	nodeList.add(patomNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce ABuiltinAtom */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAtom patomNode1;
        {
            // Block
        PTerm ptermNode2;
        TBinop tbinopNode3;
        PTerm ptermNode4;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        tbinopNode3 = (TBinop)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        patomNode1 = new ABuiltinAtom(ptermNode2, tbinopNode3, ptermNode4);
        }
	nodeList.add(patomNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AAterms1Terms */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerms ptermsNode1;
        {
            // Block
        PTerm ptermNode2;
        LinkedList listNode3 = new LinkedList();
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        {
            // Block
        }

        ptermsNode1 = new ATerms(ptermNode2, listNode3);
        }
	nodeList.add(ptermsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce AAterms2Terms */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerms ptermsNode1;
        {
            // Block
        PTerm ptermNode2;
        LinkedList listNode4 = new LinkedList();
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        ptermsNode1 = new ATerms(ptermNode2, listNode4);
        }
	nodeList.add(ptermsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce ATermTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTermTail ptermtailNode1;
        {
            // Block
        TComma tcommaNode2;
        PTerm ptermNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        ptermNode3 = (PTerm)nodeArrayList2.get(0);

        ptermtailNode1 = new ATermTail(tcommaNode2, ptermNode3);
        }
	nodeList.add(ptermtailNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AVarTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TQuestion tquestionNode2;
        TName tnameNode3;
        tquestionNode2 = (TQuestion)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);

        ptermNode1 = new AVarTerm(tquestionNode2, tnameNode3);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AStringTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        ptermNode1 = new AStringTerm(tstringliteralNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce ACompositeTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TName tnameNode2;
        TLPar tlparNode3;
        PTerms ptermsNode4;
        TRPar trparNode5;
        tnameNode2 = (TName)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        ptermsNode4 = (PTerms)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);

        ptermNode1 = new ACompositeTerm(tnameNode2, tlparNode3, ptermsNode4, trparNode5);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AQuery */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        TQueryStart tquerystartNode2;
        PLiterals pliteralsNode3;
        TDot tdotNode4;
        tquerystartNode2 = (TQueryStart)nodeArrayList1.get(0);
        pliteralsNode3 = (PLiterals)nodeArrayList2.get(0);
        tdotNode4 = (TDot)nodeArrayList3.get(0);

        pqueryNode1 = new AQuery(tquerystartNode2, pliteralsNode3, tdotNode4);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce ANamedPattern */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPattern ppatternNode1;
        {
            // Block
        TName tnameNode2;
        tnameNode2 = (TName)nodeArrayList1.get(0);

        ppatternNode1 = new ANamedPattern(tnameNode2);
        }
	nodeList.add(ppatternNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AAnyPattern */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPattern ppatternNode1;
        {
            // Block
        TStar tstarNode2;
        tstarNode2 = (TStar)nodeArrayList1.get(0);

        ppatternNode1 = new AAnyPattern(tstarNode2);
        }
	nodeList.add(ppatternNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AAbehaviour1Behaviour */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBehaviour pbehaviourNode1;
        {
            // Block
        TClassTok tclasstokNode2;
        TName tnameNode3;
        @SuppressWarnings("unused") Object nullNode4 = null;
        TLBrace tlbraceNode5;
        PClassBody pclassbodyNode6;
        TRBrace trbraceNode7;
        tclasstokNode2 = (TClassTok)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList3.get(0);
        pclassbodyNode6 = (PClassBody)nodeArrayList4.get(0);
        trbraceNode7 = (TRBrace)nodeArrayList5.get(0);

        pbehaviourNode1 = new ABehaviour(tclasstokNode2, tnameNode3, null, tlbraceNode5, pclassbodyNode6, trbraceNode7);
        }
	nodeList.add(pbehaviourNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AAbehaviour2Behaviour */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBehaviour pbehaviourNode1;
        {
            // Block
        TClassTok tclasstokNode2;
        TName tnameNode3;
        PExtends pextendsNode4;
        TLBrace tlbraceNode5;
        PClassBody pclassbodyNode6;
        TRBrace trbraceNode7;
        tclasstokNode2 = (TClassTok)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);
        pextendsNode4 = (PExtends)nodeArrayList3.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList4.get(0);
        pclassbodyNode6 = (PClassBody)nodeArrayList5.get(0);
        trbraceNode7 = (TRBrace)nodeArrayList6.get(0);

        pbehaviourNode1 = new ABehaviour(tclasstokNode2, tnameNode3, pextendsNode4, tlbraceNode5, pclassbodyNode6, trbraceNode7);
        }
	nodeList.add(pbehaviourNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce AExtends */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExtends pextendsNode1;
        {
            // Block
        TExtendsTok textendstokNode2;
        TName tnameNode3;
        textendstokNode2 = (TExtendsTok)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);

        pextendsNode1 = new AExtends(textendstokNode2, tnameNode3);
        }
	nodeList.add(pextendsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce AAclassbody1ClassBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PClassBody pclassbodyNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        }
        {
            // Block
        }

        pclassbodyNode1 = new AClassBody(listNode2, listNode3);
        }
	nodeList.add(pclassbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AAclassbody2ClassBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassBody pclassbodyNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        }

        pclassbodyNode1 = new AClassBody(listNode3, listNode4);
        }
	nodeList.add(pclassbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce AAclassbody3ClassBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassBody pclassbodyNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        }
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pclassbodyNode1 = new AClassBody(listNode2, listNode4);
        }
	nodeList.add(pclassbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AAclassbody4ClassBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PClassBody pclassbodyNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pclassbodyNode1 = new AClassBody(listNode3, listNode5);
        }
	nodeList.add(pclassbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AField */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PField pfieldNode1;
        {
            // Block
        TPrivateTok tprivatetokNode2;
        PType ptypeNode3;
        TName tnameNode4;
        TSemi tsemiNode5;
        tprivatetokNode2 = (TPrivateTok)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tnameNode4 = (TName)nodeArrayList3.get(0);
        tsemiNode5 = (TSemi)nodeArrayList4.get(0);

        pfieldNode1 = new AField(tprivatetokNode2, ptypeNode3, tnameNode4, tsemiNode5);
        }
	nodeList.add(pfieldNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TName tnameNode2;
        tnameNode2 = (TName)nodeArrayList1.get(0);

        ptypeNode1 = new AType(tnameNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce AAmethod1Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        @SuppressWarnings("unused") Object nullNode7 = null;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ppatternNode4 = (PPattern)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        trparNode8 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList5.get(0);
        pcodeNode10 = (PCode)nodeArrayList6.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList7.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, null, ppatternNode4, tlparNode5, null, null, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce AAmethod2Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        PType ptypeNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        @SuppressWarnings("unused") Object nullNode7 = null;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        trparNode8 = (TRPar)nodeArrayList5.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList6.get(0);
        pcodeNode10 = (PCode)nodeArrayList7.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList8.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, ptypeNode3, ppatternNode4, tlparNode5, null, null, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AAmethod3Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        PParams pparamsNode6;
        @SuppressWarnings("unused") Object nullNode7 = null;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ppatternNode4 = (PPattern)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        pparamsNode6 = (PParams)nodeArrayList4.get(0);
        trparNode8 = (TRPar)nodeArrayList5.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList6.get(0);
        pcodeNode10 = (PCode)nodeArrayList7.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList8.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, null, ppatternNode4, tlparNode5, pparamsNode6, null, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce AAmethod4Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        PType ptypeNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        PParams pparamsNode6;
        @SuppressWarnings("unused") Object nullNode7 = null;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        pparamsNode6 = (PParams)nodeArrayList5.get(0);
        trparNode8 = (TRPar)nodeArrayList6.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList7.get(0);
        pcodeNode10 = (PCode)nodeArrayList8.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList9.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, ptypeNode3, ppatternNode4, tlparNode5, pparamsNode6, null, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce AAmethod5Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TStar tstarNode7;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ppatternNode4 = (PPattern)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        tstarNode7 = (TStar)nodeArrayList4.get(0);
        trparNode8 = (TRPar)nodeArrayList5.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList6.get(0);
        pcodeNode10 = (PCode)nodeArrayList7.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList8.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, null, ppatternNode4, tlparNode5, null, tstarNode7, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce AAmethod6Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        PType ptypeNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TStar tstarNode7;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        tstarNode7 = (TStar)nodeArrayList5.get(0);
        trparNode8 = (TRPar)nodeArrayList6.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList7.get(0);
        pcodeNode10 = (PCode)nodeArrayList8.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList9.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, ptypeNode3, ppatternNode4, tlparNode5, null, tstarNode7, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce AAmethod7Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        PParams pparamsNode6;
        TStar tstarNode7;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ppatternNode4 = (PPattern)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        pparamsNode6 = (PParams)nodeArrayList4.get(0);
        tstarNode7 = (TStar)nodeArrayList5.get(0);
        trparNode8 = (TRPar)nodeArrayList6.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList7.get(0);
        pcodeNode10 = (PCode)nodeArrayList8.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList9.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, null, ppatternNode4, tlparNode5, pparamsNode6, tstarNode7, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce AAmethod8Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMethod pmethodNode1;
        {
            // Block
        TPublicTok tpublictokNode2;
        PType ptypeNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        PParams pparamsNode6;
        TStar tstarNode7;
        TRPar trparNode8;
        TLBrace tlbraceNode9;
        PCode pcodeNode10;
        TRBrace trbraceNode11;
        tpublictokNode2 = (TPublicTok)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        pparamsNode6 = (PParams)nodeArrayList5.get(0);
        tstarNode7 = (TStar)nodeArrayList6.get(0);
        trparNode8 = (TRPar)nodeArrayList7.get(0);
        tlbraceNode9 = (TLBrace)nodeArrayList8.get(0);
        pcodeNode10 = (PCode)nodeArrayList9.get(0);
        trbraceNode11 = (TRBrace)nodeArrayList10.get(0);

        pmethodNode1 = new AMethod(tpublictokNode2, ptypeNode3, ppatternNode4, tlparNode5, pparamsNode6, tstarNode7, trparNode8, tlbraceNode9, pcodeNode10, trbraceNode11);
        }
	nodeList.add(pmethodNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce AAcode1Code */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PCode pcodeNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        }

        pcodeNode1 = new ACode(listNode2);
        }
	nodeList.add(pcodeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce AAcode2Code */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCode pcodeNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pcodeNode1 = new ACode(listNode3);
        }
	nodeList.add(pcodeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce AAassign1Assign */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAssign passignNode1;
        {
            // Block
        @SuppressWarnings("unused") Object nullNode2 = null;
        TName tnameNode3;
        TEq teqNode4;
        tnameNode3 = (TName)nodeArrayList1.get(0);
        teqNode4 = (TEq)nodeArrayList2.get(0);

        passignNode1 = new AAssign(null, tnameNode3, teqNode4);
        }
	nodeList.add(passignNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce AAassign2Assign */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAssign passignNode1;
        {
            // Block
        PType ptypeNode2;
        TName tnameNode3;
        TEq teqNode4;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);
        teqNode4 = (TEq)nodeArrayList3.get(0);

        passignNode1 = new AAssign(ptypeNode2, tnameNode3, teqNode4);
        }
	nodeList.add(passignNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce AAassignstatement1Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        @SuppressWarnings("unused") Object nullNode2 = null;
        PExpr pexprNode3;
        TSemi tsemiNode4;
        pexprNode3 = (PExpr)nodeArrayList1.get(0);
        tsemiNode4 = (TSemi)nodeArrayList2.get(0);

        pstatementNode1 = new AAssignStatement(null, pexprNode3, tsemiNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce AAassignstatement2Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PAssign passignNode2;
        PExpr pexprNode3;
        TSemi tsemiNode4;
        passignNode2 = (PAssign)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tsemiNode4 = (TSemi)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(passignNode2, pexprNode3, tsemiNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new49() /* reduce ADeclStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PType ptypeNode2;
        TName tnameNode3;
        TSemi tsemiNode4;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);
        tsemiNode4 = (TSemi)nodeArrayList3.get(0);

        pstatementNode1 = new ADeclStatement(ptypeNode2, tnameNode3, tsemiNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new50() /* reduce AReturnStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TReturn treturnNode2;
        TName tnameNode3;
        TSemi tsemiNode4;
        treturnNode2 = (TReturn)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);
        tsemiNode4 = (TSemi)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(treturnNode2, tnameNode3, tsemiNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new51() /* reduce AAnewexpr1Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TNew tnewNode2;
        PType ptypeNode3;
        TLPar tlparNode4;
        @SuppressWarnings("unused") Object nullNode5 = null;
        TRPar trparNode6;
        tnewNode2 = (TNew)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tlparNode4 = (TLPar)nodeArrayList3.get(0);
        trparNode6 = (TRPar)nodeArrayList4.get(0);

        pexprNode1 = new ANewExpr(tnewNode2, ptypeNode3, tlparNode4, null, trparNode6);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new52() /* reduce AAnewexpr2Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TNew tnewNode2;
        PType ptypeNode3;
        TLPar tlparNode4;
        PArgs pargsNode5;
        TRPar trparNode6;
        tnewNode2 = (TNew)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tlparNode4 = (TLPar)nodeArrayList3.get(0);
        pargsNode5 = (PArgs)nodeArrayList4.get(0);
        trparNode6 = (TRPar)nodeArrayList5.get(0);

        pexprNode1 = new ANewExpr(tnewNode2, ptypeNode3, tlparNode4, pargsNode5, trparNode6);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new53() /* reduce AAcallexpr1Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TName tnameNode2;
        TDot tdotNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        TRPar trparNode7;
        tnameNode2 = (TName)nodeArrayList1.get(0);
        tdotNode3 = (TDot)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        trparNode7 = (TRPar)nodeArrayList5.get(0);

        pexprNode1 = new ACallExpr(tnameNode2, tdotNode3, ppatternNode4, tlparNode5, null, trparNode7);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new54() /* reduce AAcallexpr2Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TName tnameNode2;
        TDot tdotNode3;
        PPattern ppatternNode4;
        TLPar tlparNode5;
        PArgs pargsNode6;
        TRPar trparNode7;
        tnameNode2 = (TName)nodeArrayList1.get(0);
        tdotNode3 = (TDot)nodeArrayList2.get(0);
        ppatternNode4 = (PPattern)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        pargsNode6 = (PArgs)nodeArrayList5.get(0);
        trparNode7 = (TRPar)nodeArrayList6.get(0);

        pexprNode1 = new ACallExpr(tnameNode2, tdotNode3, ppatternNode4, tlparNode5, pargsNode6, trparNode7);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new55() /* reduce ACopyExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TName tnameNode2;
        tnameNode2 = (TName)nodeArrayList1.get(0);

        pexprNode1 = new ACopyExpr(tnameNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new56() /* reduce AAargs1Args */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PArgs pargsNode1;
        {
            // Block
        TName tnameNode2;
        LinkedList listNode3 = new LinkedList();
        tnameNode2 = (TName)nodeArrayList1.get(0);
        {
            // Block
        }

        pargsNode1 = new AArgs(tnameNode2, listNode3);
        }
	nodeList.add(pargsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new57() /* reduce AAargs2Args */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PArgs pargsNode1;
        {
            // Block
        TName tnameNode2;
        LinkedList listNode4 = new LinkedList();
        tnameNode2 = (TName)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pargsNode1 = new AArgs(tnameNode2, listNode4);
        }
	nodeList.add(pargsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new58() /* reduce AArgsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PArgsTail pargstailNode1;
        {
            // Block
        TComma tcommaNode2;
        TName tnameNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);

        pargstailNode1 = new AArgsTail(tcommaNode2, tnameNode3);
        }
	nodeList.add(pargstailNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new59() /* reduce AParam */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParam pparamNode1;
        {
            // Block
        PType ptypeNode2;
        TName tnameNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tnameNode3 = (TName)nodeArrayList2.get(0);

        pparamNode1 = new AParam(ptypeNode2, tnameNode3);
        }
	nodeList.add(pparamNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new60() /* reduce AAparams1Params */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParams pparamsNode1;
        {
            // Block
        PParam pparamNode2;
        LinkedList listNode3 = new LinkedList();
        pparamNode2 = (PParam)nodeArrayList1.get(0);
        {
            // Block
        }

        pparamsNode1 = new AParams(pparamNode2, listNode3);
        }
	nodeList.add(pparamsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new61() /* reduce AAparams2Params */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParams pparamsNode1;
        {
            // Block
        PParam pparamNode2;
        LinkedList listNode4 = new LinkedList();
        pparamNode2 = (PParam)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pparamsNode1 = new AParams(pparamNode2, listNode4);
        }
	nodeList.add(pparamsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new62() /* reduce AParamsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParamsTail pparamstailNode1;
        {
            // Block
        TComma tcommaNode2;
        PParam pparamNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pparamNode3 = (PParam)nodeArrayList2.get(0);

        pparamstailNode1 = new AParamsTail(tcommaNode2, pparamNode3);
        }
	nodeList.add(pparamstailNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new63() /* reduce ATerminal$Toplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PToplevel ptoplevelNode1;
        ptoplevelNode1 = (PToplevel)nodeArrayList1.get(0);
	if(ptoplevelNode1 != null)
	{
	  listNode2.add(ptoplevelNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new64() /* reduce ANonTerminal$Toplevel */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PToplevel ptoplevelNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        ptoplevelNode2 = (PToplevel)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptoplevelNode2 != null)
	{
	  listNode3.add(ptoplevelNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new65() /* reduce ATerminal$LiteralTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PLiteralTail pliteraltailNode1;
        pliteraltailNode1 = (PLiteralTail)nodeArrayList1.get(0);
	if(pliteraltailNode1 != null)
	{
	  listNode2.add(pliteraltailNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new66() /* reduce ANonTerminal$LiteralTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PLiteralTail pliteraltailNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pliteraltailNode2 = (PLiteralTail)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pliteraltailNode2 != null)
	{
	  listNode3.add(pliteraltailNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new67() /* reduce ATerminal$TermTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PTermTail ptermtailNode1;
        ptermtailNode1 = (PTermTail)nodeArrayList1.get(0);
	if(ptermtailNode1 != null)
	{
	  listNode2.add(ptermtailNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new68() /* reduce ANonTerminal$TermTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PTermTail ptermtailNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        ptermtailNode2 = (PTermTail)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptermtailNode2 != null)
	{
	  listNode3.add(ptermtailNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new69() /* reduce ATerminal$Field */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PField pfieldNode1;
        pfieldNode1 = (PField)nodeArrayList1.get(0);
	if(pfieldNode1 != null)
	{
	  listNode2.add(pfieldNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new70() /* reduce ANonTerminal$Field */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PField pfieldNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pfieldNode2 = (PField)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pfieldNode2 != null)
	{
	  listNode3.add(pfieldNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new71() /* reduce ATerminal$Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PMethod pmethodNode1;
        pmethodNode1 = (PMethod)nodeArrayList1.get(0);
	if(pmethodNode1 != null)
	{
	  listNode2.add(pmethodNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new72() /* reduce ANonTerminal$Method */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PMethod pmethodNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmethodNode2 = (PMethod)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmethodNode2 != null)
	{
	  listNode3.add(pmethodNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new73() /* reduce ATerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	if(pstatementNode1 != null)
	{
	  listNode2.add(pstatementNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new74() /* reduce ANonTerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PStatement pstatementNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstatementNode2 = (PStatement)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstatementNode2 != null)
	{
	  listNode3.add(pstatementNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new75() /* reduce ATerminal$ArgsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PArgsTail pargstailNode1;
        pargstailNode1 = (PArgsTail)nodeArrayList1.get(0);
	if(pargstailNode1 != null)
	{
	  listNode2.add(pargstailNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new76() /* reduce ANonTerminal$ArgsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PArgsTail pargstailNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pargstailNode2 = (PArgsTail)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pargstailNode2 != null)
	{
	  listNode3.add(pargstailNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new77() /* reduce ATerminal$ParamsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PParamsTail pparamstailNode1;
        pparamstailNode1 = (PParamsTail)nodeArrayList1.get(0);
	if(pparamstailNode1 != null)
	{
	  listNode2.add(pparamstailNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new78() /* reduce ANonTerminal$ParamsTail */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PParamsTail pparamstailNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pparamstailNode2 = (PParamsTail)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pparamstailNode2 != null)
	{
	  listNode3.add(pparamstailNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {8, SHIFT, 1}, {17, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {24, SHIFT, 5}, {25, SHIFT, 6}, },
			{{-1, ERROR, 1}, {25, SHIFT, 17}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 3}, {16, SHIFT, 18}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 6}, },
			{{-1, ERROR, 4}, {25, SHIFT, 22}, },
			{{-1, ERROR, 5}, {17, SHIFT, 23}, },
			{{-1, REDUCE, 14}, {1, SHIFT, 24}, },
			{{-1, ERROR, 7}, {26, ACCEPT, -1}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 12}, {15, SHIFT, 25}, {23, SHIFT, 26}, },
			{{-1, ERROR, 13}, {20, SHIFT, 27}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 0}, {8, SHIFT, 1}, {17, SHIFT, 2}, {18, SHIFT, 3}, {19, SHIFT, 4}, {24, SHIFT, 5}, {25, SHIFT, 6}, },
			{{-1, ERROR, 17}, {5, SHIFT, 29}, {9, SHIFT, 30}, },
			{{-1, ERROR, 18}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 6}, },
			{{-1, ERROR, 19}, {23, SHIFT, 33}, },
			{{-1, REDUCE, 9}, {12, SHIFT, 34}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 23}, {23, SHIFT, 37}, },
			{{-1, ERROR, 24}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 38}, },
			{{-1, ERROR, 25}, {16, SHIFT, 18}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 6}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 27}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 38}, },
			{{-1, REDUCE, 64}, },
			{{-1, ERROR, 29}, {25, SHIFT, 43}, },
			{{-1, REDUCE, 29}, {3, SHIFT, 44}, {4, SHIFT, 45}, },
			{{-1, ERROR, 31}, {9, SHIFT, 51}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 34}, {16, SHIFT, 18}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 6}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 10}, {12, SHIFT, 34}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 38}, {1, SHIFT, 54}, },
			{{-1, ERROR, 39}, {2, SHIFT, 55}, },
			{{-1, REDUCE, 17}, {12, SHIFT, 56}, },
			{{-1, ERROR, 41}, {23, SHIFT, 59}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 44}, {21, SHIFT, 60}, {25, SHIFT, 61}, },
			{{-1, ERROR, 45}, {25, SHIFT, 64}, },
			{{-1, ERROR, 46}, {10, SHIFT, 66}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 30}, {3, SHIFT, 44}, {4, SHIFT, 45}, },
			{{-1, REDUCE, 31}, {3, SHIFT, 44}, },
			{{-1, REDUCE, 29}, {3, SHIFT, 44}, {4, SHIFT, 45}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 54}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 38}, },
			{{-1, REDUCE, 15}, {20, REDUCE, 22}, },
			{{-1, ERROR, 56}, {17, SHIFT, 2}, {19, SHIFT, 4}, {25, SHIFT, 38}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 18}, {12, SHIFT, 56}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 34}, {1, REDUCE, 24}, },
			{{-1, ERROR, 62}, {1, SHIFT, 74}, },
			{{-1, ERROR, 63}, {21, SHIFT, 60}, {25, SHIFT, 75}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 65}, {25, SHIFT, 77}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 32}, {3, SHIFT, 44}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 70}, {10, SHIFT, 78}, },
			{{-1, ERROR, 71}, {2, SHIFT, 79}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 74}, {2, SHIFT, 80}, {21, SHIFT, 81}, {25, SHIFT, 64}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 76}, {1, SHIFT, 85}, },
			{{-1, ERROR, 77}, {14, SHIFT, 86}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 22}, },
			{{-1, ERROR, 80}, {9, SHIFT, 87}, },
			{{-1, ERROR, 81}, {2, SHIFT, 88}, },
			{{-1, ERROR, 82}, {25, SHIFT, 89}, },
			{{-1, REDUCE, 60}, {12, SHIFT, 90}, },
			{{-1, ERROR, 84}, {2, SHIFT, 93}, {21, SHIFT, 94}, },
			{{-1, ERROR, 85}, {2, SHIFT, 95}, {21, SHIFT, 96}, {25, SHIFT, 64}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, ERROR, 88}, {9, SHIFT, 107}, },
			{{-1, REDUCE, 59}, },
			{{-1, ERROR, 90}, {25, SHIFT, 64}, },
			{{-1, REDUCE, 77}, },
			{{-1, REDUCE, 61}, {12, SHIFT, 90}, },
			{{-1, ERROR, 93}, {9, SHIFT, 110}, },
			{{-1, ERROR, 94}, {2, SHIFT, 111}, },
			{{-1, ERROR, 95}, {9, SHIFT, 112}, },
			{{-1, ERROR, 96}, {2, SHIFT, 113}, },
			{{-1, ERROR, 97}, {2, SHIFT, 114}, {21, SHIFT, 115}, },
			{{-1, ERROR, 98}, {25, SHIFT, 64}, },
			{{-1, ERROR, 99}, {25, SHIFT, 117}, },
			{{-1, REDUCE, 55}, {11, SHIFT, 118}, {23, SHIFT, 119}, {25, REDUCE, 34}, },
			{{-1, ERROR, 101}, {25, SHIFT, 120}, },
			{{-1, ERROR, 102}, {10, SHIFT, 121}, },
			{{-1, ERROR, 103}, {6, SHIFT, 98}, {25, SHIFT, 122}, },
			{{-1, REDUCE, 73}, },
			{{-1, ERROR, 105}, {14, SHIFT, 124}, },
			{{-1, REDUCE, 44}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 78}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, ERROR, 111}, {9, SHIFT, 128}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, ERROR, 113}, {9, SHIFT, 130}, },
			{{-1, ERROR, 114}, {9, SHIFT, 131}, },
			{{-1, ERROR, 115}, {2, SHIFT, 132}, },
			{{-1, ERROR, 116}, {1, SHIFT, 133}, },
			{{-1, ERROR, 117}, {14, SHIFT, 134}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 119}, {21, SHIFT, 60}, {25, SHIFT, 75}, },
			{{-1, ERROR, 120}, {11, SHIFT, 136}, {14, SHIFT, 137}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 55}, {23, SHIFT, 119}, },
			{{-1, ERROR, 123}, {14, SHIFT, 138}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 74}, },
			{{-1, ERROR, 126}, {10, SHIFT, 139}, },
			{{-1, ERROR, 127}, {10, SHIFT, 140}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, ERROR, 129}, {10, SHIFT, 142}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, ERROR, 132}, {9, SHIFT, 145}, },
			{{-1, ERROR, 133}, {2, SHIFT, 146}, {25, SHIFT, 147}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 135}, {1, SHIFT, 149}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 141}, {10, SHIFT, 150}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 143}, {10, SHIFT, 151}, },
			{{-1, ERROR, 144}, {10, SHIFT, 152}, },
			{{-1, REDUCE, 43}, {6, SHIFT, 98}, {7, SHIFT, 99}, {25, SHIFT, 100}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 56}, {12, SHIFT, 154}, },
			{{-1, ERROR, 148}, {2, SHIFT, 157}, },
			{{-1, ERROR, 149}, {2, SHIFT, 158}, {25, SHIFT, 147}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 153}, {10, SHIFT, 160}, },
			{{-1, ERROR, 154}, {25, SHIFT, 161}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 57}, {12, SHIFT, 154}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 159}, {2, SHIFT, 163}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 54}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 7}, },
			{{-1, 8}, {16, 28}, },
			{{-1, 9}, },
			{{-1, 10}, },
			{{-1, 11}, },
			{{-1, 19}, {25, 41}, },
			{{-1, 35}, {36, 53}, },
			{{-1, 20}, {34, 52}, },
			{{-1, 21}, {0, 12}, {16, 12}, {18, 32}, },
			{{-1, 39}, {54, 71}, },
			{{-1, 57}, {58, 73}, },
			{{-1, 13}, {24, 40}, {27, 42}, {54, 40}, {56, 72}, },
			{{-1, 14}, },
			{{-1, 62}, {63, 76}, {119, 135}, },
			{{-1, 15}, },
			{{-1, 31}, },
			{{-1, 46}, {51, 70}, },
			{{-1, 47}, {49, 67}, },
			{{-1, 101}, {44, 63}, {45, 65}, {74, 82}, {85, 82}, {90, 82}, {98, 116}, },
			{{-1, 48}, {50, 69}, {68, 69}, },
			{{-1, 102}, {107, 126}, {110, 127}, {112, 129}, {128, 141}, {130, 143}, {131, 144}, {145, 153}, },
			{{-1, 103}, },
			{{-1, 104}, {106, 125}, },
			{{-1, 105}, {103, 123}, },
			{{-1, 148}, {149, 159}, },
			{{-1, 155}, {156, 162}, },
			{{-1, 83}, {90, 108}, },
			{{-1, 84}, {85, 97}, },
			{{-1, 91}, {92, 109}, },
			{{-1, 16}, },
			{{-1, 36}, },
			{{-1, 58}, },
			{{-1, 49}, },
			{{-1, 50}, {49, 68}, },
			{{-1, 106}, },
			{{-1, 156}, },
			{{-1, 92}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'class', string literal, '?-', '?', 'import', name",
			"expecting: name",
			"expecting: ')', ',', ':-', binop, '.'",
			"expecting: '!', string literal, '?', name",
			"expecting: string literal",
			"expecting: '(', ',', ':-', '.'",
			"expecting: EOF",
			"expecting: 'class', string literal, '?-', '?', 'import', name, EOF",
			"expecting: ':-', '.'",
			"expecting: binop",
			"expecting: 'extends', '{'",
			"expecting: string literal, '?', name",
			"expecting: '.'",
			"expecting: ',', '.'",
			"expecting: 'public', 'private', '}'",
			"expecting: '{'",
			"expecting: '('",
			"expecting: ')'",
			"expecting: ')', ','",
			"expecting: ',', ':-', '.'",
			"expecting: '*', name",
			"expecting: '}'",
			"expecting: 'public', '}'",
			"expecting: ',', ':-', binop, '.'",
			"expecting: '(', '*', name",
			"expecting: '(', name",
			"expecting: ')', '*', name",
			"expecting: ';'",
			"expecting: ')', ',', ':-', '.'",
			"expecting: ')', ',', '*'",
			"expecting: ')', '*'",
			"expecting: 'new', 'return', '}', name",
			"expecting: '=', ';', '.', name",
			"expecting: 'new', name",
			"expecting: '=', ';'",
			"expecting: ';', '.'",
			"expecting: ')', name",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 1, 4, 5, 6, 7, 7, 7, 7, 8, 9, 7, 7, 7, 10, 11, 12, 13, 13, 2, 12, 11, 3, 7, 11, 7, 1, 14, 15, 13, 7, 3, 13, 13, 7, 16, 17, 18, 12, 19, 15, 20, 1, 21, 14, 22, 14, 22, 14, 13, 13, 11, 23, 11, 18, 18, 7, 16, 24, 16, 20, 25, 1, 7, 14, 22, 22, 21, 17, 18, 18, 26, 16, 16, 27, 7, 28, 15, 17, 1, 29, 30, 26, 14, 31, 15, 29, 1, 29, 29, 15, 17, 15, 17, 30, 1, 1, 32, 1, 21, 33, 31, 27, 31, 31, 29, 29, 31, 15, 31, 15, 15, 17, 16, 27, 33, 20, 34, 22, 35, 27, 31, 31, 21, 21, 31, 21, 31, 31, 15, 36, 31, 16, 33, 31, 31, 22, 22, 21, 22, 21, 21, 31, 27, 18, 17, 36, 22, 22, 22, 21, 1, 18, 18, 27, 27, 17, 22, 18, 18, 27, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
