/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class ABuiltinAtom extends PAtom
{
    private PTerm _lhs_;
    private PBinop _binop_;
    private PTerm _rhs_;

    public ABuiltinAtom()
    {
        // Constructor
    }

    public ABuiltinAtom(
        @SuppressWarnings("hiding") PTerm _lhs_,
        @SuppressWarnings("hiding") PBinop _binop_,
        @SuppressWarnings("hiding") PTerm _rhs_)
    {
        // Constructor
        setLhs(_lhs_);

        setBinop(_binop_);

        setRhs(_rhs_);

    }

    @Override
    public Object clone()
    {
        return new ABuiltinAtom(
            cloneNode(this._lhs_),
            cloneNode(this._binop_),
            cloneNode(this._rhs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABuiltinAtom(this);
    }

    public PTerm getLhs()
    {
        return this._lhs_;
    }

    public void setLhs(PTerm node)
    {
        if(this._lhs_ != null)
        {
            this._lhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lhs_ = node;
    }

    public PBinop getBinop()
    {
        return this._binop_;
    }

    public void setBinop(PBinop node)
    {
        if(this._binop_ != null)
        {
            this._binop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._binop_ = node;
    }

    public PTerm getRhs()
    {
        return this._rhs_;
    }

    public void setRhs(PTerm node)
    {
        if(this._rhs_ != null)
        {
            this._rhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rhs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lhs_)
            + toString(this._binop_)
            + toString(this._rhs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lhs_ == child)
        {
            this._lhs_ = null;
            return;
        }

        if(this._binop_ == child)
        {
            this._binop_ = null;
            return;
        }

        if(this._rhs_ == child)
        {
            this._rhs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lhs_ == oldChild)
        {
            setLhs((PTerm) newChild);
            return;
        }

        if(this._binop_ == oldChild)
        {
            setBinop((PBinop) newChild);
            return;
        }

        if(this._rhs_ == oldChild)
        {
            setRhs((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
