/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class AConfigToplevel extends PToplevel
{
    private PConfig _config_;

    public AConfigToplevel()
    {
        // Constructor
    }

    public AConfigToplevel(
        @SuppressWarnings("hiding") PConfig _config_)
    {
        // Constructor
        setConfig(_config_);

    }

    @Override
    public Object clone()
    {
        return new AConfigToplevel(
            cloneNode(this._config_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConfigToplevel(this);
    }

    public PConfig getConfig()
    {
        return this._config_;
    }

    public void setConfig(PConfig node)
    {
        if(this._config_ != null)
        {
            this._config_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._config_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._config_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._config_ == child)
        {
            this._config_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._config_ == oldChild)
        {
            setConfig((PConfig) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
