/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class ADeclareToplevel extends PToplevel
{
    private PDeclare _declare_;

    public ADeclareToplevel()
    {
        // Constructor
    }

    public ADeclareToplevel(
        @SuppressWarnings("hiding") PDeclare _declare_)
    {
        // Constructor
        setDeclare(_declare_);

    }

    @Override
    public Object clone()
    {
        return new ADeclareToplevel(
            cloneNode(this._declare_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclareToplevel(this);
    }

    public PDeclare getDeclare()
    {
        return this._declare_;
    }

    public void setDeclare(PDeclare node)
    {
        if(this._declare_ != null)
        {
            this._declare_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declare_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declare_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declare_ == child)
        {
            this._declare_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declare_ == oldChild)
        {
            setDeclare((PDeclare) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
