/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class ANamedblock extends PNamedblock
{
    private TName _name_;
    private TStringLiteral _context_;
    private TLBrace _lBrace_;
    private PCode _code_;
    private TRBrace _rBrace_;

    public ANamedblock()
    {
        // Constructor
    }

    public ANamedblock(
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") TStringLiteral _context_,
        @SuppressWarnings("hiding") TLBrace _lBrace_,
        @SuppressWarnings("hiding") PCode _code_,
        @SuppressWarnings("hiding") TRBrace _rBrace_)
    {
        // Constructor
        setName(_name_);

        setContext(_context_);

        setLBrace(_lBrace_);

        setCode(_code_);

        setRBrace(_rBrace_);

    }

    @Override
    public Object clone()
    {
        return new ANamedblock(
            cloneNode(this._name_),
            cloneNode(this._context_),
            cloneNode(this._lBrace_),
            cloneNode(this._code_),
            cloneNode(this._rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANamedblock(this);
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TStringLiteral getContext()
    {
        return this._context_;
    }

    public void setContext(TStringLiteral node)
    {
        if(this._context_ != null)
        {
            this._context_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._context_ = node;
    }

    public TLBrace getLBrace()
    {
        return this._lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(this._lBrace_ != null)
        {
            this._lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrace_ = node;
    }

    public PCode getCode()
    {
        return this._code_;
    }

    public void setCode(PCode node)
    {
        if(this._code_ != null)
        {
            this._code_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._code_ = node;
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._context_)
            + toString(this._lBrace_)
            + toString(this._code_)
            + toString(this._rBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._context_ == child)
        {
            this._context_ = null;
            return;
        }

        if(this._lBrace_ == child)
        {
            this._lBrace_ = null;
            return;
        }

        if(this._code_ == child)
        {
            this._code_ = null;
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._context_ == oldChild)
        {
            setContext((TStringLiteral) newChild);
            return;
        }

        if(this._lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(this._code_ == oldChild)
        {
            setCode((PCode) newChild);
            return;
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
