/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class APositiveLiteral extends PLiteral
{
    private PAtom _atom_;

    public APositiveLiteral()
    {
        // Constructor
    }

    public APositiveLiteral(
        @SuppressWarnings("hiding") PAtom _atom_)
    {
        // Constructor
        setAtom(_atom_);

    }

    @Override
    public Object clone()
    {
        return new APositiveLiteral(
            cloneNode(this._atom_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPositiveLiteral(this);
    }

    public PAtom getAtom()
    {
        return this._atom_;
    }

    public void setAtom(PAtom node)
    {
        if(this._atom_ != null)
        {
            this._atom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atom_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atom_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atom_ == child)
        {
            this._atom_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atom_ == oldChild)
        {
            setAtom((PAtom) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
