/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class AQuery extends PQuery
{
    private TQueryStart _queryStart_;
    private PLiterals _literals_;
    private TDot _dot_;

    public AQuery()
    {
        // Constructor
    }

    public AQuery(
        @SuppressWarnings("hiding") TQueryStart _queryStart_,
        @SuppressWarnings("hiding") PLiterals _literals_,
        @SuppressWarnings("hiding") TDot _dot_)
    {
        // Constructor
        setQueryStart(_queryStart_);

        setLiterals(_literals_);

        setDot(_dot_);

    }

    @Override
    public Object clone()
    {
        return new AQuery(
            cloneNode(this._queryStart_),
            cloneNode(this._literals_),
            cloneNode(this._dot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQuery(this);
    }

    public TQueryStart getQueryStart()
    {
        return this._queryStart_;
    }

    public void setQueryStart(TQueryStart node)
    {
        if(this._queryStart_ != null)
        {
            this._queryStart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._queryStart_ = node;
    }

    public PLiterals getLiterals()
    {
        return this._literals_;
    }

    public void setLiterals(PLiterals node)
    {
        if(this._literals_ != null)
        {
            this._literals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._literals_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._queryStart_)
            + toString(this._literals_)
            + toString(this._dot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._queryStart_ == child)
        {
            this._queryStart_ = null;
            return;
        }

        if(this._literals_ == child)
        {
            this._literals_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._queryStart_ == oldChild)
        {
            setQueryStart((TQueryStart) newChild);
            return;
        }

        if(this._literals_ == oldChild)
        {
            setLiterals((PLiterals) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
