/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import java.util.*;
import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class ATerms extends PTerms
{
    private PTerm _term_;
    private final LinkedList<PTermTail> _termTail_ = new LinkedList<PTermTail>();

    public ATerms()
    {
        // Constructor
    }

    public ATerms(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") List<PTermTail> _termTail_)
    {
        // Constructor
        setTerm(_term_);

        setTermTail(_termTail_);

    }

    @Override
    public Object clone()
    {
        return new ATerms(
            cloneNode(this._term_),
            cloneList(this._termTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerms(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public LinkedList<PTermTail> getTermTail()
    {
        return this._termTail_;
    }

    public void setTermTail(List<PTermTail> list)
    {
        this._termTail_.clear();
        this._termTail_.addAll(list);
        for(PTermTail e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._termTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._termTail_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        for(ListIterator<PTermTail> i = this._termTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTermTail) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
