/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class AThrowStatement extends PStatement
{
    private TThrow _throw_;
    private TName _name_;
    private TSemi _semi_;

    public AThrowStatement()
    {
        // Constructor
    }

    public AThrowStatement(
        @SuppressWarnings("hiding") TThrow _throw_,
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setThrow(_throw_);

        setName(_name_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AThrowStatement(
            cloneNode(this._throw_),
            cloneNode(this._name_),
            cloneNode(this._semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAThrowStatement(this);
    }

    public TThrow getThrow()
    {
        return this._throw_;
    }

    public void setThrow(TThrow node)
    {
        if(this._throw_ != null)
        {
            this._throw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._throw_ = node;
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._throw_)
            + toString(this._name_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._throw_ == child)
        {
            this._throw_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._throw_ == oldChild)
        {
            setThrow((TThrow) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
