/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class AVarTerm extends PTerm
{
    private TQuestion _question_;
    private TName _name_;

    public AVarTerm()
    {
        // Constructor
    }

    public AVarTerm(
        @SuppressWarnings("hiding") TQuestion _question_,
        @SuppressWarnings("hiding") TName _name_)
    {
        // Constructor
        setQuestion(_question_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new AVarTerm(
            cloneNode(this._question_),
            cloneNode(this._name_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarTerm(this);
    }

    public TQuestion getQuestion()
    {
        return this._question_;
    }

    public void setQuestion(TQuestion node)
    {
        if(this._question_ != null)
        {
            this._question_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._question_ = node;
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._question_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._question_ == child)
        {
            this._question_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._question_ == oldChild)
        {
            setQuestion((TQuestion) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
