/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class TAtTok extends Token
{
    public TAtTok()
    {
        super.setText("@");
    }

    public TAtTok(int line, int pos)
    {
        super.setText("@");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtTok(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtTok text.");
    }
}
