/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class TDeclareTok extends Token
{
    public TDeclareTok()
    {
        super.setText("declare");
    }

    public TDeclareTok(int line, int pos)
    {
        super.setText("declare");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDeclareTok(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDeclareTok(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDeclareTok text.");
    }
}
