/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class TIfDl extends Token
{
    public TIfDl()
    {
        super.setText(":-");
    }

    public TIfDl(int line, int pos)
    {
        super.setText(":-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIfDl(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIfDl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIfDl text.");
    }
}
