/* This file was generated by SableCC (http://www.sablecc.org/). */

package eu.serscis.sam.node;

import eu.serscis.sam.analysis.*;

@SuppressWarnings("nls")
public final class TTry extends Token
{
    public TTry()
    {
        super.setText("try");
    }

    public TTry(int line, int pos)
    {
        super.setText("try");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTry(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTry(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTry text.");
    }
}
